name = "portofolio-new"
type = "javascript"
account_id = "fd5d72f860336cfd95d5785b820d7dff"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "."       # folder root project
entry-point = "."
